# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Temporal
email: cadence-group@uber.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.temporal.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compact
permalink: /:path/:title

# GitHub changable settings
encoding: UTF-8
future: true
jailed: false
gfm_quirks: paragraph_end

# GitHub unchangable setings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

# Code content collection
collections:
  code_content:
    output: true

# Defaults
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "doc"
  -
    scope:
      path: "tour"
    values:
      layout: "tour"
  # -
  #   scope:
  #     path: "docs/01_how_cadence_works.md"
  #   values:
  #     redirect_from: docs/how_cadence_works


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
